### ISSUE TITLE
[FEATURE-TRACKING] Use Standard Error messages for ksctl logs 🛣️

### ISSUE THREAD

**Issue by dipankardas011** [ksctl/ksctl#165]
# Is your feature request related to a problem?📖
currently all the error messages are like random strings
no standardization of error messages available

# Describe the solution you'd like 👨‍💻👩‍💻
some pseudo const error messages will be nice to have

### What are the Sub-Action items?
- [x] Add Initial Error Consts #194
- [x] #329
- [ ] Use in K3s
- [ ] Use in Azure
- [ ] Use in Aws
- [ ] Use in Local
- [ ] Fix the log.NewError()

> [!NOTE]
> we can use the log.NewError() and keep the package key value for now if we get that it is not necessary then we can remove it

# Provider in question
you have to choose the branch according to the task
> [!TIP]
> 1. each new branch for each cloud provider or pkg/ which are updated
> 2. create a branch for this Issue as a main branch and create those sub-branches and dest to this issue main branch and finally open a PR for this mani branch to finally update and merge to the project main branch

## Additional context
the list of error code is not a exhaustive list
make sure the destination branch is `165-feature-use-standard-error-messages`
Check [Contribution's guidelines](https://kubesimplify.github.io/ksctl/docs/contributions)

**Comment by dipankardas011** [comment]
Like for every response
It should {code: "some standard code of error", reason: "err.Error()", more...}

**Comment by dipankardas011** [comment]
// Usage Example
```go

import github.com/kubesimplify/ksctl/pkg/utils/errors

func main() {
    errors.ErrInvalidRegion.wrap(err)   // Returns a error type
    // Here the err is the err generated
}
```

**Comment by harisheoran** [comment]
Can I work on this?

**Comment by dipankardas011** [comment]
sure

**Comment by dipankardas011** [comment]
@harisheoran I haven't thought of any good error wraps yet, so we need to decide on them as we go

need help cc @prateek041

**Comment by harisheoran** [comment]
> @harisheoran I haven't thought of any good error wraps yet, so we need to decide on them as we go
> 
> need help cc @prateek041

Hey @prateek041 , can we discuss on this

**Comment by dipankardas011** [comment]
Error stack trace

it would be nice if the NewError can wrap the package name as well I think it does still
