### ISSUE TITLE
feature(cloud): Addition of AWS support

### ISSUE THREAD

**Issue by dipankardas011** [ksctl/ksctl#17]
# Is your feature request related to a problem?📖
adding support for aws cloud for EKS and HA self-managed clusters

# Describe the solution you'd like 👨‍💻👩‍💻

```[tasklist]
### Tasks
- [x] Make the clients abstracted by an interface for doing mocks
- [x] continuously create unit test files
- [x] make the helper functions in the helper.go
- [ ] add documentation for aws
- [x] connect them to the controller/cloud
- [ ] add functionality for get and switch
- [ ] HA cluster done
- [ ] EKS done
```

# Describe alternatives you've considered💠
NONE

# Provider in question
aws

## Additional context
Check [Contribution's guidelines](https://kubesimplify.github.io/ksctl/docs/contributions)

📖 Reference Guide https://github.com/weaveworks/eksctl/tree/main/pkg/ctl
https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#pkg-examples
https://www.pulumi.com/registry/packages/aws/api-docs/

**Comment by dipankardas011** [comment]
* Create https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#example_EKS_CreateCluster_shared00
* List https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#example_EKS_ListClusters_shared00
* Describe https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#example_EKS_DescribeCluster_shared00
* Delete https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#example_EKS_DeleteCluster_shared00

**Comment by dipankardas011** [comment]
For now I have opened the PR for terrraform implementation 
- #65

**Comment by dipankardas011** [comment]
> For now I have opened the PR for terrraform implementation
> 
> * [[HA](aws) Terraform module for illustration purpose #65](https://github.com/kubesimplify/ksctl/pull/65)

Do check out the info

**Comment by riteshsonawane1372** [comment]
I want to give it a try @dipankardas011. You can assign me.

**Comment by dipankardas011** [comment]
## NOTE!

do create the PR to `dev` branch till further updates

**Comment by riteshsonawane1372** [comment]
> ## NOTE!
> do create the PR to `dev` branch till further updates

Can you update the dev branch to current main branch ?

**Comment by Horiodino** [comment]
i would like to work on it unofficial if its not planned , can i !!! , and i also give you updates what i have done . ...

**Comment by dipankardas011** [comment]
> i would like to work on it unofficial if its not planned , can i !!! , and i also give you updates what i have done . ...

Sure you can progress and once the interfaces and core functionality are added you can jump and add them😎

**Comment by dipankardas011** [comment]
# Note
Use aws go sdk v2

**Comment by dipankardas011** [comment]
DEV-1

**Comment by dipankardas011** [comment]
Fixes DEV-1
