### ISSUE TITLE
[FEATURE-TRACKING] WASM workernode support 🛣️

### ISSUE THREAD

**Issue by dipankardas011** [ksctl/ksctl#178]
# Feature description

It aims to make the Ksctl application install to have each application to have hybrid option of install for max flexiablity and also to be able to have sequence of installtion and destroy steps to better entry and exit logic. Reason is complex stack requirements we will need these support for each application and also for ksctl-application-stack we will also need to define dependencies so that prod-monitoring stack can be achieved

Once that is fixed we can move forward with kube-spin and later we can gather steps how to add custom implementation from wasmtime and wasmedge directly

## Why do we need it?
adding WASM workernode support for HA cluster and cloud managed clusters

## What it will bring?
able to provision WASM workloads. it will utilize https://www.spinkube.dev/

### Action Items
- [x] Hybrid Option of Installation with proper cleanup for each ksctlApplication support #401
- [x] Get the versioning of sub components right. like if its a stack each stack's component should have its own versioning so need to figure that out #413
- [x] Custom fields for install like `namespaceBasedInstall`, `withoutUI`, etc #413
- [x] Change the latest mapping for main to develop -> main so as the current naming is not the standard #424
- [x] Initial work on production apps which can be taken up (Issue: #220) after this issue is completed
- [x] kube-spin (PR: #429)
- [x] custom wasm support directly with wasi runtimes (wasmtime, wasmedge) (PR: #435)
  - Using kwasm

**Comment by dipankardas011** [comment]
It's open

**Comment by Aditya1404Sal** [comment]
Commenting here for my request of shadow assist on this issue

**Comment by dipankardas011** [comment]
## Important consideration before we jump to implementations

spin-kube (our first attainable goal): https://www.spinkube.dev/docs/spin-operator/installation/installing-with-helm/

from the currrent workflow we will need to modify the structure of a application defined in the package `internal/kubernetes/`

to make it contain the hybrid of kubectl apply commands as well as helm commands
so that we can use a single struct to define all the components

problem is we need to reconsider how the ksctl-application-controller's crd looks like and may need to allomodate the changes

and it can be a good time to anaylise how can we support the production ready stacks as these hydird stacks can be a initial steps in achieving those

cc @saiyam1814

**Comment by dipankardas011** [comment]
Also @Horiodino will be working on this next, Hoping to avoid git conflicts with your merge ;)

**Comment by dipankardas011** [comment]
## Current Plan for the Ksctl application setup

### Phase 1
- initial prototype for the application types
- transition to the new application types

### Phase 2
- more options accomodation
- whether to use helm or kubectl based (when available)
- namespace selection, namespace level or cluster wide deployment, with UI or without UI
- provide the options in the crd via the override key in the component stack
```yaml
app: nice
version: latest
options:
  namespace: x
  clusterWideDeployment: true
```
we could use
```go
Options map[string]any
```


### Phase
