### ISSUE TITLE
[ACTION-TRACKING] Support ksctl applications stacks

### ISSUE THREAD

**Issue by dipankardas011** [ksctl/ksctl#179]
# Is your feature request related to a problem?📖
ksctl only provide functionality for cloud provider related resources automation
missing kubernetes side automation

# Describe the solution you'd like 👨‍💻👩‍💻
installing pre-installed applications when the cluster is created and also when the cluster has already been created

it has it avoid the use of kubectl commands and instead use some form of kUbernetes client go or any other client go like helm ...

# Describe alternatives you've considered💠
manual creation is not what ksctl's goal which is simplify and make it a good platform for anyone to manage clusters

# Provider in question
- K3s
- Kubeadm
- Civo (HA, managed)
- Local (managed)
- Azure (HA, managed)

### Tasks
- [x] add support in managed clusters
- [x] configure the distributions (k3s, kubeadm) to handle custom CNI to be installed later
- [x] add Devops tools
- [x] add monitoring stacks
- [x] service mesh

### List of Applications and CNI plugins
- [x] Argo-CD
- [x] Argo-Rollouts
- [x] Prometheus Operator
- [ ] Kyverno
- [ ] Loadbalancer (Nginx) (CNI) (_OPTIONAL_) as we might need to change a lot of things
- [x] Istio
- [ ] Linkerd
- [x] Cilium (CNI)
- [x] Flannel (CNI)
- [ ] Kubernetes Dashboard
- [ ] Kubevela
- [ ] Flux
- [ ] Jenkins
- [ ] Litmus Chaos
- [ ] Loki
- [ ] kubeseal for sealed secrets
- [ ] different types of loadbalancer or support for gateway api

> **Note**
the CNI and Apps must be separate from each other
for CNI plugins we must disable the default cni like in k3s its flannel

## List of all the applications and cni support
- argocd
- argo-rollouts
- cilium (cni)
- istio
- prometheus-stack

## Additional context
Check [Contribution's guidelines](https://kubesimplify.github.io/ksctl/docs/contributions)

**Comment by SD-13** [comment]
@dipankardas011 Can you please assign me.

**Comment by dipankardas011** [comment]
@SD-13 Here is quick way for you to get started
https://gitlab.com/dipankardas011/go-playground/-/tree/main/k8s-go
I hope it helps

also it does not represent how the ksctl should work with this but it helps you better understand and do some stuffs

**Comment by SD-13** [comment]
Please feel free to take this up. Thanks

**Comment by dipankardas011** [comment]
> Please feel free to take this up. Thanks

Sure thanks

**Comment by dipankardas011** [comment]
next extension (App): https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack

**Comment by dipankardas011** [comment]
Closing this in favour of other app specific issues
