### ISSUE TITLE
[Enhancement Tracking]: Improve & Fix some of the Ksctl internal code 🛣️

### ISSUE THREAD

**Issue by dipankardas011** [ksctl/ksctl#334]
### Enhancement Title

Remove Unused components and fix some of them

### Summary of the Enhancement

- [x] GRPC ksctl agent unit testing. Some helper link https://pkg.go.dev/google.golang.org/grpc/test/bufconn, https://github.com/grpc/grpc-go/blob/master/test/bufconn/bufconn.go (#362)
- [x] Standadize the environment variables used for stopping certain features and os.GetEnv("TES_FLAG...) (#363)
- [x] Fix the plan on how to perform releases and the version code for docker images and their manifests (#361)
- [x] make sure of we can get the workerNode and other components to get joined even if the certificate and the keys get expired. for testing this out we can define the expire to be 20 minutes and then we can try to perform the operation (#366)
- [x] Os version updates
- [x] IMprove the exponential backoff inconsitences in the implementation (#370)
- [x] Set timezones for vms (#364)
- [x] Seperate the manager.go implementation from one to multiple managers like for only ha another for fetching data, managed, manager for kubernetes related tasks only,... (#365)
- [x] Make the environment variable not set as Note type message (#364)
- [x] ~~ssh executor is failing with something that is weird~~ (⚠️ Unable to reproduce)

```log
2024-05-15T10:12:09.9785281Z {"time":"2024-05-15T10:12:09.978109441Z","level":"WARN","msg":"RETRYING","component":"bootstrap","msgType":"WARN","reason":"dial tcp 131.153.226.231:22: connect: connection refused"}
2024-05-15T10:12:11.2170484Z {"time":"2024-05-15T10:12:11.216608586Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"moving the downloaded binaries to specific location"}
2024-05-15T10:12:12.1193148Z {"time":"2024-05-15T10:12:12.118966431Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"store the certificate files"}
2024-05-15T10:12:12.3327943Z {"time":"2024-05-15T10:12:12.332416862Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"configure etcd configuration file and systemd"}
2024-05-15T10:12:12.5085991Z {"time":"2024-05-15T10:12:12.508219611Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"restart the systemd and start etcd service"}
2024-05-15T10:12:13.0747725Z {"time":"2024-05-15T10:12:13.074287554Z","level":"WARN","msg":"RETRYING","component":"bootstrap","msgType":"WARN","reason":"ssh: handshake failed: read tcp 10.0.0.4:53054->131.153.227.53:22: read: connection reset by peer"}
2024-05-15T10:12:13.3066062Z {"time":"2024-05-15T10:12:13.306267622Z","level":"INFO","msg":"Successful in executing the script","component":"bootstrap","msgType":"SUCCESS"}
2024-05-15T10:12:13.3068565Z {"time":"2024-05-15T10:12:13.306359723Z","level":"INFO","msg":"configured DataStore","component":"bootstrap","msgType":"SUCCESS","number":"0"}
2024-05-15T10:12:20.9337979Z {"time":"2024-05-15T10:12:20.933498291Z","level":"INFO","msg":"Exec Scripts","component":"bootstrap"}
2024-05-15T10:12:20.9339935Z {"time":"2024-05-15T10:12:20.933524092Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"fetch etcd binaries and cleanup"}
2024-05-15T10:12:22.8695486Z {"time":"2024-05-15T10:12:22.869228268Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"moving the downloaded binaries to specific location"}
2024-05-15T10:12:24.0330621Z {"time":"2024-05-15T10:12:24.032757325Z","level":"INFO","msg":"Exec Scripts","component":"bootstrap"}
2024-05-15T10:12:24.0332581Z {"time":"2024-05-15T10:12:24.032787326Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"fetch etcd binaries and cleanup"}
2024-05-15T10:12:24.3713248Z {"time":"2024-05-15T10:12:24.370853956Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"store the certificate files"}
2024-05-15T10:12:25.9435970Z {"time":"2024-05-15T10:12:25.943199575Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"moving the downloaded binaries to specific location"}
2024-05-15T10:12:27.0220919Z {"time":"2024-05-15T10:12:27.021725771Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"store the certificate files"}
2024-05-15T10:12:34.1035786Z {"time":"2024-05-15T10:12:34.103211057Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"enable and start systemd service for haproxy"}
2024-05-15T10:12:34.9681396Z {"time":"2024-05-15T10:12:34.967829019Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"create haproxy configuration"}
2024-05-15T10:12:35.1401188Z {"time":"2024-05-15T10:12:35.139811418Z","level":"INFO","msg":"Executing Sub-Script","component":"bootstrap","name":"restarting haproxy"}
2024-05-15T10:12:35.4093997Z {"time":"2024-05-15T10:12:35.408584978Z","level":"INFO","msg":"Successful in executing the script","component":"bootstrap","msgType":"SUCCESS"}
2024-05-15T10:12:35.4096119Z {"time":"2024-05-15T10:12:35.408778781Z","level":"INFO","msg":"configured LoadBalancer","component":"bootstrap","msgType":"SUCCESS"}
2024-05-15T10:28:57.3958280Z {"time":"2024-05-15T10:28:57.395198366Z","level":"ERROR","msg":"handled error","catch":"Failure in executing script%!(EXTRA string=component, string=bootstrap, string=Reason, *errors.errorString=EOF, string=stderr, string=)"}
2024-05-15T10:28:57.3960989Z {"time":"2024-05-15T10:28:57.395294967Z","level":"INFO","msg":"Local Storage Got Killed","component":"local","msgType":"SUCCESS"}
2024-05-15T10:28:57.3964029Z {"time":"2024-05-15T10:28:57.395309367Z","level":"ERROR","msg":"Failure","err":"Failure in executing script%!(EXTRA string=component, string=bootstrap, string=Reason, *errors.errorString=EOF, string=stderr, string=)"}
2024-05-15T10:28:57.3975308Z exit status 1
```
- [x] Need to fix logging for cloudProvider credentials part and remove the cloud provider credentials export (#342)
- [x] TODOs (#351)
- [x] use the pkg/helpers/utilities to for deep copy where its needed (#351)
- [x] improve the naming convention and avoid the wrapping of additional package in the log.NewError and instead use the return err if its not the soruce of creation for the error (#342)
- [x] need to fix the multiple types of the VM worknodes as only one nodetype can be saved on the worknode better one would be to leave it as it is and enable the storing of the nodeSizes in array and the index to tell us the what is the type of the node
Update and check the state document is completely utilized aka no information is missed. add a array of workernode VMSize along with the count of workernodes if we are allowing dynamic size of workernodes to be able to add (#354) (#246)
- [x] see if any struct or functions are not ment to be used outside the scope of pkg (#351)
- [x] add boilderplace thing like what kubebuilder and other tools do. LICENSE and author... (#342)
example
```
# Copyright 2023 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
```

- [x] we can do is stop using the storageImporter and instead run a temporary pod which hosts a ksctl storage server and when we want it we deploy it and tell it to use the storageDriver.Kubernetes to import the state by this we can use the suggested method from the above PR to use kubectl api server sirect call to send the data in raw json. once done we can delete the pod after that only we will deploy the **ksctl agent**. by this we can elemiate the http server and we can stick to grpc and we can eliminate the over complication of storageImporter controller and crds... (#343)
- [x] If possible try to use context.Context (aka a better use of them) (#342)
- [x] Handle panics (#342)
- [x] SSH client failing (quite unique issue)
<img width="1470" alt="image" src="https://github.com/ksctl/ksctl/assets/65275144/97e19c7d-52b8-4cdc-825a-5c6a379500bb"> (#343)

- [x] Ha cluster cleanup fails , make the noOfCP, noOfWp, setter functions to invoke just after state is init is done so that we can be saved from data loss even if the graceful termination is added as the DeleVM needs them to be there for us to work in deletion otherwise it will fail (#351)
<img width="985" alt="image" src="https://github.com/ksctl/ksctl/assets/65275144/2a61a608-91b9-4955-8acc-c03972c9538e">

- [x] Security vulnerablity detected on mysql database when stateimport http server recives the exposrted data
- [x] make sure if all the newInterface assignment functions are returning concerete type as return type and let the user handle the var \<var\> interface = ??? (#350)
- [x] ~~add context based cli logging (exploit the context) https://github.com/vito/progrock~~

- [x] failed to install istio in macos (helm repo update is the error message which is needed) (#355)
```
[PASS] Done adding kubernetes ksctl specific controllers
[PASS] Done with installing ksctl k8s specific tools
[ERR] handled error catch=App install failed component=kubernetes-client app=storage.Application{Name:"istio", Version:"latest"} Reason=failed to locate chart component=kubernetes-client Reason=no cached repo found. (try 'helm repo update'): open /Users/dipankardas/.cache/helm/repository/istio-index.yaml: no such file or directory


[PASS] Local Storage Got Killed
[ERR] Failure err=App install failed component=kubernetes-client app=storage.Application{Name:"istio", Version:"latest"} Reason=failed to locate chart component=kubernetes-client Reason=no cached repo found. (try 'helm repo update'): open /Users/dipankardas/.cache/helm/repository/istio-index.yaml: no such file or directory


exit status 1
```

### Motivation and Goals

It will help enable to remove unwanted codebases

### Detailed Design

> [!NOTE]
> Document the changes and changelog as well

### Scope of changes

- [x] Cli
- [x] UI
- [x] Docs

### Agreement

- [X] I agree to engage in constructive discussion and follow the Contribution Guidelines.

**Comment by dipankardas011** [comment]
<img width="985" alt="image" src="https://github.com/ksctl/ksctl/assets/65275144/2a61a608-91b9-4955-8acc-c03972c9538e">

**Comment by dipankardas011** [comment]
> <img alt="image" width="985" src="https://private-user-images.githubusercontent.com/65275144/328774862-2a61a608-91b9-4955-8acc-c03972c9538e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjU3MTYsIm5iZiI6MTcxNTIyNTQxNiwicGF0aCI6Ii82NTI3NTE0NC8zMjg3NzQ4NjItMmE2MWE2MDgtOTFiOS00OTU1LThhY2MtYzAzOTcyYzk1MzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAzMzAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYzM1ZWUxNzRiZTc1ZjNiNzM1ZTkxZWQ2NTU4MjIxMTU0NWNlNTM3Y2Y1ZWViMDFhMmZmNzk4Yjk3NWQ2MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.adql-smrZ3-ibHSHSAVhCWhqCthQe7XAgJwJXXhjaSo">

it happens when the the code stops at vpc creation and other stuff and when you want to delete them it fails

the reason of failure was the deleteCLuster first tries to delete the VMs as the noOfDs was not initialized before starting to create the VPC and other stuff what we can do is
**Create**: we can modify it to first save the configuration to the state about the user requirement make the VM []
so that these error can be avoided

**Comment by dipankardas011** [comment]
> [!CAUTION]
> I am force all the context.TODO() and context.Background() already present to use the package specific context

cc @Horiodino

**Comment by dipankardas011** [comment]
Improve the loading screen like some go routine that we are waiting for some information

or wait operation

```go
package main

import (
	"fmt"
	"time"

	"github.com/briandowns/spinner"
)

func main() {
	for i := 0; i <= 43; i++ {
		fmt.Println("i:", i)
		do(i)
	}
}

func do(i int) {
	s := spinner.New(spinner.CharSets[i], 100*time.Millisecond) // Build our new spinner
	s.Start()                                                   // Start the spinner
	time.Sleep(4 * time.Second)                                 // Run for some time to simulate work
	s.Stop()
}
```

**Comment by dipankardas011** [comment]
## Some discussion on ksctl component release cycle

For example
new tag -> v1.2.0

#### Sol 1
in the package formed it will use this v1.2.0 version of the image only
some variable will be needed for storing each ksctl component version

#### Sol 2
if the ksctl apps manifests (deployment, services, pods, ...) are there in a specific loc

then we don't need to wait for them to be

```
func installApplication(struct{ Name: "ksctl-stateimport", Version: "v1.1.4" })
```
then we don't need to maintain these manifest specific to version

as it will be in speicif clocation
`ksctl-components/manifests/**`

**Comment by dipankardas011** [comment]
we would also need to think on for each release there has to be one file or something which will contain the latest stable release version for these components

and in predetermined location like the above mentioned

so proposal is `ksctl-components/manifests/[state-import, agent, ...]/install.yml`

and then we can provide tags to relach in specific branch

> [!WARNING]
> constraint: all the release must have this directory`

**Comment by dipankardas011** [comment]
we can learn from this
![image](https://github.com/ksctl/ksctl/assets/65275144/f7e1e6f6-df53-4140-b235-b64d5747dca2)

**Comment by dipankardas011** [comment]
> we can learn from this
Improved the generalLogger

**Comment by dipankardas011** [comment]
also try to make the implementations for mocks in the test cases only

**Comment by dipankardas011** [comment]
Need to investagate on this error

`Bug` `civo` `managed`

```
{"time":"2024-05-22T17:33:38.81591668Z","level":"INFO","msg":"Started to configure Cluster to add Ksctl specific storage","component":"kubernetes-client"}
{"time":"2024-05-22T17:33:38.815926202Z","level":"INFO","msg":"creating ksctl namespace","component":"kubernetes-client","name":"ksctl"}
{"time":"2024-05-22T17:33:39.06779658Z","level":"INFO","msg":"creating service account for ksctl agent","component":"kubernetes-client","name":"ksctl-sa"}
{"time":"2024-05-22T17:33:39.150461265Z","level":"INFO","msg":"creating clusterrole","component":"kubernetes-client","name":"ksctl-agent-crole"}
{"time":"2024-05-22T17:33:39.234801452Z","level":"INFO","msg":"creating clusterrolebinding","component":"kubernetes-client","name":"ksctl-agent-croleb"}
{"time":"2024-05-22T17:33:39.318191118Z","level":"INFO","msg":"creating ksctl state transfer pod","component":"kubernetes-client","name":"ksctl-state-importer"}
{"time":"2024-05-22T17:33:39.5035[68](https://github.com/ksctl/ksctl/actions/runs/9195349229/job/25291175559#step:4:69)483Z","level":"WARN","msg":"retrying current no of success","component":"kubernetes-client","msgType":"WARN","status.Phase":"Pending","status.Reason":""}
{"time":"2024-05-22T17:33:44.581762607Z","level":"WARN","msg":"retrying current no of success","component":"kubernetes-client","msgType":"WARN","status.Phase":"Pending","status.Reason":""}
{"time":"2024-05-22T17:34:29.58395594Z","level":"ERROR","msg":"handled error","catch":"pod get failed%!(EXTRA string=component, string=kubernetes-client, string=Reason, *url.Error=Get \"https://74.220.19.73:6443/api/v1/namespaces/ksctl/pods/ksctl-state-importer\": http2: client connection lost)"}
{"time":"2024-05-22T17:34:29.58402275Z","level":"INFO","msg":"Local Storage Got Killed","component":"local","msgType":"SUCCESS"}
{"time":"2024-05-22T17:34:29.584034494Z","level":"ERROR","msg":"Failure","err":"pod get failed%!(EXTRA string=component, string=kubernetes-client, string=Reason, *url.Error=Get \"https://74.220.19.[73](https://github.com/ksctl/ksctl/actions/runs/9195349229/job/25291175559#step:4:74):6443/api/v1/namespaces/ksctl/pods/ksctl-state-importer\": http2: client connection lost)"}
```
