### ISSUE TITLE
[PLANNER]: Roadmap v1.2.2

### ISSUE THREAD

**Issue by dipankardas011** [ksctl/ksctl#371]
## Goals to Achieve
- [ ] add Info method to ksctl manager
- [ ] graceful termination
- [ ] Wasm Support
- [ ] AWS EKS and stablity of AWS provider
- [ ] **(Optional)** GCP support
- [ ] add nodes improvements (Check issue on ksctl/cli)
- [ ] remove the use of cli to install pre-installed apps and instead use the application controller
- [ ] Add Application to the Stack
  - Cert Manager
  -

**Comment by saiyam1814** [comment]
cluster autoscaler and WASM support <3

**Comment by saiyam1814** [comment]
Looks good!
