### ISSUE TITLE
enhancement: Add firewall rules for the HA cluster on various providers

### ISSUE THREAD

**Issue by dipankardas011** [ksctl/ksctl#87]
# Is your feature request related to a problem?📖 
all ports are accessible by public internet

# Describe the solution you'd like 👨‍💻👩‍💻
need to open specific ports from specific src & destination
- [K3s](https://docs.k3s.io/installation/requirements?os=debian#inbound-rules-for-k3s-nodes)
- [Kubeadm](https://kubernetes.io/docs/reference/networking/ports-and-protocols)

# Describe alternatives you've considered💠

### Tasks
- [ ] Azure VM SecurityGroup
- [ ] Civo Firewall rules
- [ ] Aws security groups
- [x] review K3s and Kubeadm required ports

**Comment by Horiodino** [comment]
can you share the file path it will be more easy !

**Comment by dipankardas011** [comment]
https://github.com/kubesimplify/ksctl/blob/a80b79bbda2b86a8b6cd87d57a4c2708ceaa1f47/api/azure/loadbalancer.go#L53-L97

**Comment by dipankardas011** [comment]
> https://github.com/kubesimplify/ksctl/blob/a80b79bbda2b86a8b6cd87d57a4c2708ceaa1f47/api/azure/loadbalancer.go#L53-L97

this is one of the part

**Comment by dipankardas011** [comment]
do be mindful inorder to test if the things are working fine you have to create clusters

**Comment by dipankardas011** [comment]
https://docs.k3s.io/installation/requirements#inbound-rules-for-k3s-server-nodes

**Comment by dipankardas011** [comment]
You all can check the 
**Networking** section in the below reference https://github.com/Netcracker/KubeMarine/blob/main/documentation/Installation.md#prerequisites-for-cluster-nodes
